INSERT INTO movies (
    title,
    language,
    duration_minutes,
    genre,
    release_date,
    active,
    description,
    poster_url,
    banner_image_url,
    trailer_url,
    certification,
    imdb_id,
    rating,
    popularity_score,
    featured,
    created_at,
    updated_at
) VALUES

      ('Avengers: Endgame', 'English', '180', 'Action', '2019-04-26', true,
       'Epic Marvel finale',
       'https://img.com/avengers.jpg',
       'https://img.com/avengers-banner.jpg',
       'https://youtube.com/watch?v=avengers',
       'UA',
       'tt4154796',
       8.4,
       95,
       true,
       NOW(),
       NOW()),

      ('Inception', 'English', '148', 'Sci-Fi', '2010-07-16', true,
       'Mind-bending sci-fi thriller',
       'https://img.com/inception.jpg',
       'https://img.com/inception-banner.jpg',
       'https://youtube.com/watch?v=inception',
       'UA',
       'tt1375666',
       8.8,
       90,
       false,
       NOW(),
       NOW()),

      ('Interstellar', 'English', '169', 'Sci-Fi', '2014-11-07', true,
       'Space exploration epic',
       'https://img.com/interstellar.jpg',
       'https://img.com/interstellar-banner.jpg',
       'https://youtube.com/watch?v=interstellar',
       'UA',
       'tt0816692',
       8.6,
       88,
       false,
       NOW(),
       NOW()),

      ('RRR', 'Telugu', '182', 'Action', '2022-03-25', true,
       'Freedom fighter action drama',
       'https://img.com/rrr.jpg',
       'https://img.com/rrr-banner.jpg',
       'https://youtube.com/watch?v=rrr',
       'UA',
       'tt8178634',
       8.0,
       85,
       true,
       NOW(),
       NOW()),

      ('KGF Chapter 2', 'Kannada', '168', 'Action', '2022-04-14', true,
       'Rocky Bhai returns',
       'https://img.com/kgf2.jpg',
       'https://img.com/kgf2-banner.jpg',
       'https://youtube.com/watch?v=kgf2',
       'UA',
       'tt10698680',
       8.3,
       87,
       true,
       NOW(),
       NOW()),

      ('Dangal', 'Hindi', '161', 'Sports', '2016-12-23', true,
       'Wrestling biopic',
       'https://img.com/dangal.jpg',
       'https://img.com/dangal-banner.jpg',
       'https://youtube.com/watch?v=dangal',
       'U',
       'tt5074352',
       8.4,
       80,
       false,
       NOW(),
       NOW()),

      ('Parasite', 'Korean', '132', 'Thriller', '2019-05-30', true,
       'Oscar winning thriller',
       'https://img.com/parasite.jpg',
       'https://img.com/parasite-banner.jpg',
       'https://youtube.com/watch?v=parasite',
       'A',
       'tt6751668',
       8.5,
       75,
       false,
       NOW(),
       NOW()),

      ('Spirited Away', 'Japanese', '125', 'Animation', '2001-07-20', true,
       'Studio Ghibli masterpiece',
       'https://img.com/spiritedaway.jpg',
       'https://img.com/spiritedaway-banner.jpg',
       'https://youtube.com/watch?v=spiritedaway',
       'U',
       'tt0245429',
       8.6,
       70,
       false,
       NOW(),
       NOW());